### ISSUE TITLE
能增加OPLUS 3t机型吗？

### ISSUE THREAD

**Issue by dmcimi** [exthmui-legacy/android#11]
开发团队你们好！虽说OPLUS 3t很久远了，但很想有该项目的ROM适配，如果不能望告知（

**Comment by isning** [comment]
虽然很久了，但还是回答一下（抱歉😂）
目前这个机型没有维护者，同时，我们的团队里也没有人有这个机子，云适配不太可能，还是要等有人维护才行，或者是自己拉代码、拉tree编译一个UNOFFICIAL，同时如果您愿意成为我们的官方维护者，我们也是很欢迎的
