### ISSUE TITLE
希望添加功能及功能改进

### ISSUE THREAD

**Issue by ghost** [exthmui-legacy/android#17]
1.农历gkd
2.希望有天气应用，可以试试几何天气
3.希望Aplayer可以通过coolapk更新
4.深色模式的日落日出判定无效
5.小窗模式有时消失

**Comment by isning** [comment]
第2项不太可能
其他的也就只能先当个坑了，不知道有没有人来填

**Comment by ghost** [comment]
都去搞11分支去了 哈哈哈

**Comment by isning** [comment]
主要是本来人也不够

**Comment by ghost** [comment]
[笑哭]

**Comment by zknb-666** [comment]
> 第2项不太可能
> 其他的也就只能先当个坑了，不知道有没有人来填

RR都有天气的啊

**Comment by BlueSword03** [comment]
开发组好像跟一个开发组合作搞天气了，但是咕咕咕到现在
