### ISSUE TITLE
什么时候支持红米note7

### ISSUE THREAD

**Issue by RaymondChang1204** [exthmui-legacy/android#4]
什么时候支持红米note7 和索尼xz 和索尼xzp

**Comment by kmou424** [comment]
ROM尚处于开发阶段，不会对外支持机型，（开发）期间流出的ROM均为内部测试版本

**Comment by kmou424** [comment]
ROM尚处于开发阶段，不会对外支持机型，（开发）期间流出的ROM均为内部测试版本，对外机型支持列表将会在ROM正式发布后确定
