### ISSUE TITLE
自行编译该ROM开机后，发现启动器，输入法，后台等应用无预装

### ISSUE THREAD

**Issue by Asgore-Dreemur** [exthmui-legacy/android#41]
## 设备信息
型号: Xiaomi Redmi 5 plus  
代号: vince  
CPU: msm8953 arm64  

## ROM信息
exThmUI版本: 11.0-20230901-NUCLEAR-SNAPSHOT-vince-Vanilla  
Android 版本: 11  
内核版本: 4.9.337  

## 问题  
使用了[这里](https://github.com/dib12/local_manifest) lineage-18.1 分支的manifest来下载设备树，内核使用[这里](https://github.com/aospa-vince/android_kernel_xiaomi_vince) topaz分支  
编译后成功开机，但是一直卡在**正在启动系统**  
也没有预装的例如`AOSP键盘`的输入法  
我使用adb安装了启动器和输入法，工作正常  
但`最近的任务`即后台无法唤出，我使用的是三键导航，按下任务键后无反应  
另外，我没有找到除了开机向导外的任何能够更改导航方式的方法  

##  其他
以前xda里就翻到了这个ROM，但是官网`exthmui.cn`无法访问，并且github上的官方设备支持列表也变成了404  
不想用android 13，又想自己编译一个rom试试，所以尝试了exthmui-11  
一开始使用crd的设备树卡第一屏，然后用los的官方设备树卡第二屏  
希望该问题能够得到解决，无论是**仓库的特性**还是**我的问题**，真的挺想用这个rom的  
感谢awa

**Comment by isning** [comment]
原因大概是makefile include错了，找某个官方的设备树照着ify一下？
还有，项目已经archive了哦

**Comment by Asgore-Dreemur** [comment]
> 原因大概是makefile include错了，找某个官方的设备树照着ify一下？ 还有，项目已经archive了哦

exthmui的官方设备支持仓库[这里](https://github.com/exthmui-devices)好像没了，我甚至找不到其他设备的exthmui支持的设备树  
ify是啥qwq，没搜到  
该仓库我看好像没有archive，是`准备archive`/`archive了但是没设`?

**Comment by Asgore-Dreemur** [comment]
很多申请官方/社区开发者的issue中给的设备树都是404

**Comment by isning** [comment]
是后面那一个，那个组织好像是被删掉了，你可以去找找之前主要开发者的个人仓库里的设备树，也可能能找到

**Comment by Asgore-Dreemur** [comment]
我在github上全局搜索了带有`exthm`字样的Makefile文件，没有找到任何关于vince的exthm设备树（

**Comment by hiper25** [comment]
我的建议是 如果你用LOS的tree 就得配合用LOS的vendor跟kernel
看了下 我觉得你可以直接使用LOS的tree开编译
开eng看看有没有什么问题 没问题的话直接切userdebug用就可以了

**Comment by Asgore-Dreemur** [comment]
> 我的建议是 如果你用LOS的tree 就得配合用LOS的vendor跟kernel 看了下 我觉得你可以直接使用LOS的tree开编译 开eng看看有没有什么问题 没问题的话直接切userdebug用就可以了

已经尝试过，使用los的device和vendor  
los的kernel有bug，用了aospa-vince的  
卡第二屏

**Comment by hiper25** [comment]
> > 我的建议是 如果你用LOS的tree 就得配合用LOS的vendor跟kernel 看了下 我觉得你可以直接使用LOS的tree开编译 开eng看看有没有什么问题 没问题的话直接切userdebug用就可以了
> 
> 已经尝试过，使用los的device和vendor los的kernel有bug，用了aospa-vince的 卡第二屏

那直接去修bug就可以了 
用aospa-vince只会加重病情（

**Comment by Asgore-Dreemur** [comment]
> > > 我的建议是 如果你用LOS的tree 就得配合用LOS的vendor跟kernel 看了下 我觉得你可以直接使用LOS的tree开编译 开eng看看有没有什么问题 没问题的话直接切userdebug用就可以了
> > 
> > 
> > 已经尝试过，使用los的device和vendor los的kernel有bug，用了aospa-vince的 卡第二屏
> 
> 那直接去修bug就可以了 用aospa-vince只会加重病情（

上边写的报错信息是某个结构体少了某个成员，好像没法改（

**Comment by Asgore-Dreemur** [comment]
> > > > 我的建议是 如果你用LOS的tree 就得配合用LOS的vendor跟kernel 看了下 我觉得你可以直接使用LOS的tree开编译 开eng看看有没有什么问题 没问题的话直接切userdebug用就可以了
> > > 
> > > 
> > > 已经尝试过，使用los的device和vendor los的kernel有bug，用了aospa-vince的 卡第二屏
> > 
> > 
> > 那直接去修bug就可以了 用aospa-vince只会加重病情（
> 
> 上边写的报错信息是某个结构体少了某个成员，好像没法改（

我尝试了其他rom的内核，仍然是卡第二屏，看样子好像不是内核问题

**Comment by Asgore-Dreemur** [comment]
> 原因大概是makefile include错了，找某个官方的设备树照着ify一下？ 还有，项目已经archive了哦

后续我会尝试exthmui-13，马上开学了没时间，先关掉issue，感谢各位的帮助  
另外能否请您加入一个QQ群，我们需要这样的大佬来 ~~解决问题~~ **帮助我们**，如果不行也没关系的qwq  
835361653
