### ISSUE TITLE
[feature request] 请求添加 答录机 功能

### ISSUE THREAD

**Issue by rhjdvsgsgks** [exthmui-legacy/android#5]
rt，之前在找相关应用的时候看有开发者说即使获取了 root 也无法只通过一个应用实现，所以很冒昧的来请求一下，不知能否通过这种第三方 rom 实现

**Comment by Yuyuko1024** [comment]
有点意思，先加个todo

**Comment by rhjdvsgsgks** [comment]
是放弃这个这个功能了吗？

**Comment by SakuraiLH** [comment]
目前有两种实现答录机的方式
1.拨打运营商指定的语音邮箱
2.软件自动接收电话
第一种请联系您的运营商，
第二种要实现过于复杂，且用户群体较少。
如果呼声很高的话会考虑去添加的，谢谢您的issue。

**Comment by ghost** [comment]
> 是放弃这个这个功能了吗？

目前有两种实现答录机的方式
1.拨打运营商指定的语音邮箱
2.软件自动接收电话
第一种请联系您的运营商，
第二种要实现过于复杂，且用户群体较少。
如果呼声很高的话会考虑去添加的，谢谢您的issue。
